# Generated by Django 4.2.16 on 2026-01-14 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
            options={
                'db_table': 'otp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_used'], name='otp_email_778f9e_idx'), models.Index(fields=['created_at'], name='otp_created_e4248b_idx')],
            },
        ),
    ]
