# Generated by Django 4.2.16 on 2026-01-14 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('time_limit', models.PositiveIntegerField(default=60, help_text='Time limit in seconds', validators=[django.core.validators.MinValueValidator(10)])),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LIVE', 'Live'), ('ENDED', 'Ended')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'db_table': 'quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qualification_limit', models.PositiveIntegerField(help_text='Number of top participants to qualify for next round')),
                ('is_active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'round',
                'ordering': ['round_no'],
            },
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status'], name='quiz_status_ab1832_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['slug'], name='quiz_slug_9eab84_idx'),
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.round'),
        ),
        migrations.AddField(
            model_name='participant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quizzes.quiz'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['quiz', 'round_no'], name='round_quiz_id_3381f9_idx'),
        ),
        migrations.AddIndex(
            model_name='round',
            index=models.Index(fields=['is_active'], name='round_is_acti_ab1478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('quiz', 'round_no')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['round', 'order'], name='question_round_i_d3f7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['quiz', 'email'], name='participant_quiz_id_abc96a_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['verified'], name='participant_verifie_eed19b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('quiz', 'email')},
        ),
    ]
