# Generated by Django 4.2.16 on 2026-01-14 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='participant',
            name='participant_quiz_id_abc96a_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='participant_verifie_eed19b_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='question_round_i_d3f7d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='round',
            name='round_quiz_id_3381f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='round',
            name='round_is_acti_ab1478_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='quizzes_qui_status_376889_idx',
            old_name='quiz_status_ab1832_idx',
        ),
        migrations.RenameIndex(
            model_name='quiz',
            new_name='quizzes_qui_slug_2477f3_idx',
            old_name='quiz_slug_9eab84_idx',
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='qualification_limit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='participant',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
        migrations.AlterModelTable(
            name='round',
            table=None,
        ),
    ]
