# Generated by Django 4.2.16 on 2026-01-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_participant_participant_quiz_id_abc96a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='qualification_done',
            field=models.BooleanField(default=False),
        ),
    ]
