# Generated by Django 4.2.16 on 2026-01-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_round_qualification_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_qualified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
