# Generated by Django 4.2.16 on 2026-03-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_rename_roundattempt_quizattempt_and_more'),
        ('quizzes', '0004_participant_is_qualified_alter_participant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_participants', to='quizzes.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'email')},
            },
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_qualified',
        ),
        migrations.RemoveField(
            model_name='question',
            name='round',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
