# Generated by Django 4.2.16 on 2026-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_allowedparticipant_remove_participant_is_qualified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
