# Generated by Django 4.2.16 on 2026-03-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_participant_has_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='show_leaderboard',
            field=models.BooleanField(default=False),
        ),
    ]
