# Generated by Django 4.2.16 on 2026-03-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quiz_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='cheat_score',
            field=models.IntegerField(default=0),
        ),
    ]
