# Generated by Django 4.2.16 on 2026-03-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_add_cheat_score'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_status_376889_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quizzes_qui_slug_2477f3_idx',
        ),
    ]
