# Generated by Django 4.2.16 on 2026-01-14 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.PositiveIntegerField(help_text='Time taken in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.question')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.round')),
            ],
            options={
                'db_table': 'attempt',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['participant', 'round'], name='attempt_partici_53ae98_idx'), models.Index(fields=['question'], name='attempt_questio_b40335_idx'), models.Index(fields=['is_correct'], name='attempt_is_corr_23909a_idx')],
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
