# Generated by Django 4.2.16 on 2026-01-16 11:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_participant_is_qualified_alter_participant_email'),
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='attempt_partici_53ae98_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='attempt_questio_b40335_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='attempt_is_corr_23909a_idx',
        ),
        migrations.AlterField(
            model_name='attempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.participant'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.round'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='selected_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='time_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='attempt',
            table=None,
        ),
        migrations.AddField(
            model_name='questionsession',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.participant'),
        ),
        migrations.AddField(
            model_name='questionsession',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question'),
        ),
        migrations.AddField(
            model_name='questionsession',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.round'),
        ),
        migrations.AlterUniqueTogether(
            name='questionsession',
            unique_together={('participant', 'question')},
        ),
    ]
