# Generated by Django 4.2.16 on 2026-01-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_participant_is_qualified_alter_participant_email'),
        ('attempts', '0002_questionsession_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.participant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.round')),
            ],
            options={
                'unique_together': {('participant', 'round')},
            },
        ),
    ]
