# Generated by Django 4.2.16 on 2026-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_roundattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='selected_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
