# Generated by Django 4.2.16 on 2026-03-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_participant_is_qualified_alter_participant_email'),
        ('attempts', '0004_alter_attempt_selected_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoundAttempt',
            new_name='QuizAttempt',
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='round',
        ),
        migrations.RemoveField(
            model_name='questionsession',
            name='round',
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsession',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('participant', 'quiz')},
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='round',
        ),
    ]
