# Generated by Django 4.2.16 on 2026-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0005_rename_roundattempt_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsession',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
