# Generated by Django 4.2.16 on 2026-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0006_add_order_to_question_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
